---
- name: Using secret variable file to create local user on managed hosts
  hosts: servera
  vars_files:
    - secret.yml
  tasks:
    - name: Create {{user}} user with encrypted password on serverc
      ansible.builtin.user:
        name: "{{user}}"
        password: "{{ pwhash | password_hash('sha512') }}"
        state: present
