---
- name: Play1 - Using variable for configure Apache web server on managed host.
  hosts: serverb
  vars:
    web_pkg: httpd
    web_svc: httpd
  tasks:
    - name: P1-Task1 - install {{web_pkg}} package on serverb.
      ansible.builtin.yum:
        name: "{{web_pkg}}"
        state: present
    
    - name: P1-Task2 - start and enable {{web_svc}} service on serverb
      ansible.builtin.service:
        name: "{{web_svc}}"
        state: started
        enabled: true

    - name: P1-Task3 - Add or Insert html file on serverb
      ansible.builtin.copy:
        content: "Hello world from ansible"
        dest: /var/www/html/index.html

- name: Play2 - Using variable files for configure DB on managed host.
  hosts: serverb
  vars_files:
    - var/db.yml
  tasks:
    - name: P2-Task1 - install {{db_pkg}} package on serverb
      ansible.builtin.dnf:
        name: "{{db_pkg}}"
        state: installed

    - name: P2-Task2 - Start {{db_svc}} service on serverb
      ansible.builtin.systemd:
        name: "{{db_svc}}"
        state: started
